spring:
  cloud:
    gateway:
      routes:
        - id: ms-account
          uri: lb://ms-account
          predicates:
          - Path=/api/accounts/**
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
          - Path=/api/customers/**
        - id: ms-product
          uri: lb://ms-product
          predicates:
          - Path=/api/products/**
        - id: ms-transaction
          uri: lb://ms-transaction
          predicates:
          - Path=/api/transactions/**
        - id: ms-wallet-bootcoin
          uri: lb://ms-wallet-bootcoin
          predicates:
          - Path=/api/bootcoin/**
server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
